language: go
sudo: required
go:
  - 1.13.x

before_install:

script:
  - make build
  - make test
  - make check
  - make coverage

after_success:
  # send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash) -f "!mock.go"
