name: VectorSQL Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make build
